-- Versionierung fuer gespeicherte Bibliotheks-Prompts.
-- Bestehende Prompts werden mit ihrem aktuellen Zustand als Version 1 uebernommen.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

alter table public.library
  add column current_version integer not null default 1,
  add column updated_at timestamptz;

update public.library
set updated_at = coalesce(created_at, timezone('utc'::text, now()))
where updated_at is null;

alter table public.library
  alter column updated_at set default timezone('utc'::text, now()),
  alter column updated_at set not null;

alter table public.library
  add constraint library_current_version_positive
  check (current_version > 0);

create table public.prompt_versions (
  id bigint generated by default as identity primary key,
  prompt_id bigint not null references public.library(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  version_number integer not null check (version_number > 0),
  name text not null,
  fields jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  restored_from_version integer check (
    restored_from_version is null or restored_from_version > 0
  ),
  constraint prompt_versions_prompt_version_unique
    unique (prompt_id, version_number)
);

create index prompt_versions_user_prompt_idx
  on public.prompt_versions (user_id, prompt_id, version_number desc);

alter table public.prompt_versions enable row level security;

create policy "Pro users can view own prompt versions"
on public.prompt_versions
for select
to authenticated
using (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.tier = 'pro'
  )
);

revoke all on table public.prompt_versions from anon, authenticated;
grant select on table public.prompt_versions to authenticated;
grant select, insert, update, delete on table public.prompt_versions to service_role;
grant usage, select on sequence public.prompt_versions_id_seq to service_role;

-- Das bestehende breite UPDATE-Recht wuerde auch die neuen Systemspalten
-- current_version/updated_at freigeben. Nutzer duerfen nur fachliche Felder aendern.
revoke update on table public.library from authenticated;
grant update (name, fields, category) on table public.library to authenticated;

insert into public.prompt_versions (
  prompt_id,
  user_id,
  version_number,
  name,
  fields,
  created_at
)
select
  library.id,
  library.user_id,
  1,
  library.name,
  library.fields,
  coalesce(library.created_at, timezone('utc'::text, now()))
from public.library;

create or replace function private.prepare_library_prompt_version()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  force_version boolean :=
    coalesce(current_setting('promptomizer.force_version', true), 'off') = 'on';
begin
  if tg_op = 'INSERT' then
    new.current_version := 1;
    new.updated_at := coalesce(
      new.created_at,
      timezone('utc'::text, now())
    );
  elsif old.name is distinct from new.name
     or old.fields is distinct from new.fields
     or force_version then
    new.current_version := old.current_version + 1;
    new.updated_at := timezone('utc'::text, now());
  else
    new.current_version := old.current_version;
    new.updated_at := old.updated_at;
  end if;

  return new;
end;
$$;

create or replace function private.record_library_prompt_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := (select auth.uid());
  force_version boolean :=
    coalesce(current_setting('promptomizer.force_version', true), 'off') = 'on';
  restored_version integer :=
    nullif(
      current_setting('promptomizer.restore_from_version', true),
      ''
    )::integer;
begin
  if caller_id is not null and caller_id <> new.user_id then
    raise exception 'PROMPT_VERSION_OWNER_MISMATCH'
      using errcode = '42501';
  end if;

  if tg_op = 'INSERT'
     or old.name is distinct from new.name
     or old.fields is distinct from new.fields
     or force_version then
    insert into public.prompt_versions (
      prompt_id,
      user_id,
      version_number,
      name,
      fields,
      created_at,
      restored_from_version
    )
    values (
      new.id,
      new.user_id,
      new.current_version,
      new.name,
      new.fields,
      new.updated_at,
      case when tg_op = 'UPDATE' then restored_version else null end
    );
  end if;

  return new;
end;
$$;

revoke all on function private.prepare_library_prompt_version() from public;
revoke all on function private.record_library_prompt_version() from public;

create trigger prepare_library_prompt_version
before insert or update on public.library
for each row
execute function private.prepare_library_prompt_version();

create trigger record_library_prompt_version
after insert or update on public.library
for each row
execute function private.record_library_prompt_version();

create or replace function public.restore_library_prompt_version(
  p_prompt_id bigint,
  p_version_number integer
)
returns setof public.library
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_version public.prompt_versions%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'AUTH_REQUIRED'
      using errcode = '42501';
  end if;

  select prompt_versions.*
  into selected_version
  from public.prompt_versions
  where prompt_versions.prompt_id = p_prompt_id
    and prompt_versions.version_number = p_version_number
    and prompt_versions.user_id = (select auth.uid());

  if not found then
    raise exception 'PROMPT_VERSION_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  perform set_config('promptomizer.force_version', 'on', true);
  perform set_config(
    'promptomizer.restore_from_version',
    p_version_number::text,
    true
  );

  return query
  update public.library
  set
    name = selected_version.name,
    fields = selected_version.fields
  where library.id = p_prompt_id
    and library.user_id = (select auth.uid())
  returning library.*;
end;
$$;

revoke all on function public.restore_library_prompt_version(bigint, integer)
  from public, anon;
grant execute on function public.restore_library_prompt_version(bigint, integer)
  to authenticated, service_role;
